title: Atelier Fans de Terre Colombes
theme: jekyll-theme-cayman
url: "https://fansdeterre.com" # the base hostname & protocol for your site
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate 
  - jekyll-redirect-from 
---
title: Jekyll Redirect 301 - stage
redirect_from:
  - https://fansdeterre.com/stages-et-evenements-cours-poterie-ceramique-colombes/
permalink: /pages/stages_adultes
---
title: Jekyll Redirect 301 - kdo
redirect_from:
  - https://fansdeterre.com/offrir/
permalink: /pages/bon_kdo
---
title: Jekyll Redirect 301 - raku
redirect_from:
  - https://fansdeterre.com/stages-et-evenements-cours-poterie-ceramique-colombes/raku-paris/
permalink: /pages/raku_adultes
---
title: Jekyll Redirect 301 - atelier
redirect_from:
  - https://fansdeterre.com/cours-stages-poterie-ceramique-colombes/l-atelier-cours-de-poterie-ceramique-colombes/
permalink: /pages/atelier  
defaults:
  -
    scope:
      path:            "assets/**"
    values:
      sitemap:         false

timezone: Europe/Paris
tagline: Cours et Stages de poterie
author: Monika Jacques-Gustave
social:
  links:
    - https://www.facebook.com/fansdeterre/
    - https://www.instagram.com/fans_de_terre/