title: Atelier Fans de Terre - Cours et Stages de poterie et céramique
description: Atelier de poterie situé à Colombes dans les Hauts-de-Seine, près de Paris. 
Vous avez le choix ! Cours de poterie, Stage débutant céramique, Stage Raku, Cours enfant,..
theme: jekyll-theme-cayman
plugins:
  - jemoji
  - jekyll-seo-tag
  
